[package]
name = "fine-lncs"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["rainei"]
license = "MIT"
description = "A modified version of Jozott's Springer Lecture Notes in Computer Science (LNCS) Typst template."
repository = "https://github.com/ra1nei/typst-fine-lncs"
keywords = [
    "LLNCS",
    "LNCS",
    "paper",
    "Lecture Notes in Computer Science",
    "Springer",
    "Computer Science",
]
categories = ["paper"]
disciplines = ["computer-science"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

[tool]
